// Package publish places generated bytes at the location the install address
// answers from.
//
// The generator produces bytes and is told nothing about where they go. This
// package is the only part that knows, and that separation is the point rather
// than tidiness: decisions/manifest-address.md makes the address permanent and
// says nothing about the storage behind it, so the storage has to be movable
// while the address stands still. Moving it is an edit to Stable below and to
// nothing else.
//
// The write is atomic from a reader's side. A reader here is a Jellyfin server
// polling one address on its own schedule, so it arrives in the middle of a run
// as often as not. The bytes go to a temporary file beside the target and are
// renamed over it, and a run that fails before the rename leaves the previously
// published file byte-identical.
//
// What that shape exists against is not a lost update. A server that fetches a
// truncated manifest cannot parse it, shows an empty repository and reports no
// error, which is the same thing it shows for an address that was never right.
// The next run would replace the truncated file and the symptom would clear, so
// whoever was told about it would find nothing to look at.
//
// Two runs overlapping are safe for the same reason and not by a lock. Each run
// writes its own temporary file, so the target holds one run's whole output or
// the other's and never a mixture of the two. Which of them wins is a different
// question and is not answered here; a schedule that must not race itself is
// #32.
//
// How the placed file is served is the host's and not this code's. Measured
// against a file already published from the served directory:
//
//	curl -sS -D - -o /dev/null https://flowfin.dev/design-tokens.json
//	HTTP/1.1 200 OK
//	Server: GitHub.com
//	Content-Type: application/json; charset=utf-8
//	Cache-Control: max-age=600
//
// Run 2026-08-10. The content type a server expects comes from the file name,
// and the ten minutes are the host's default rather than a value this
// repository sets, which is the reason the measurement is here: it is a fact
// about somebody else's server that a placement into a different directory
// would silently change.
package publish

import (
	"bytes"
	"crypto/sha256"
	"errors"
	"fmt"
	"io"
	"os"
	"path/filepath"

	"flowfin.dev/hub/internal/site"
)

// Target is a place bytes are published to, relative to the repository root.
//
// It is a value rather than two constants because a published address is a
// directory and a file name together and the two are settled in different
// places, so the pair travels as one thing. Entry 5 of #1 settled on one
// published address, finished builds only, which is why there is one target
// below; a second would be another value rather than an edit to this one.
type Target struct {
	// Dir is the directory the file is placed in.
	Dir string

	// Name is the file's name, and the last segment of the address that
	// answers with it.
	Name string
}

// Path is where the target lands under root.
func (t Target) Path(root string) string {
	return filepath.Join(root, filepath.FromSlash(t.Dir), t.Name)
}

// Stable is where the finished catalogue is published.
//
// The directory is site.Dir rather than a second copy of the same word, so a
// site that is served from somewhere else takes the manifest with it instead of
// leaving it behind at an address that then answers with a file nothing
// updates.
var Stable = Target{Dir: site.Dir, Name: "manifest.json"}

// mode is what the placed file is readable as.
//
// os.CreateTemp makes a file only its owner can read, and a manifest that
// arrives at the served directory unreadable is served as a refusal or not at
// all, which a Jellyfin server shows as an empty repository and no error. The
// bit is set explicitly rather than left to the umask for that reason.
const mode = 0o644

// Placement is what a run did to the catalogue an operator reads.
//
// A run that regenerated exactly the bytes already published and a run that
// replaced them are the same syscalls and the same nil error, and #32 asks for
// them to be different words in the output. The distinction cannot be taken
// after the fact from the file's size or its modification time, because both
// move when identical bytes are rewritten, so it is taken here, where the old
// bytes and the new ones are both in reach.
//
// What it is not is a statement about which of two overlapping runs the address
// ends up holding. This verdict is about the bytes the address answered with
// when this run read it, and a run whose neighbour renamed over it in between
// reports against what it saw. Serialising the two is #32's concurrency group.
type Placement int

const (
	// NotPlaced is what a run that returned an error carries.
	//
	// It is first so that it is the zero value. A caller that ignores the error
	// and prints the placement is then told nothing was placed, rather than
	// being told by a failed run that the catalogue changed.
	NotPlaced Placement = iota

	// Changed is a run whose bytes differ from what the address answered with,
	// including the first run at an address nothing was published at.
	Changed

	// Unchanged is a run that produced exactly the bytes already published.
	//
	// It is a success and not a failure. A catalogue that nothing has released
	// into since the last run has nothing to write, and the schedule in #32
	// reaches this on most of its runs.
	Unchanged
)

func (p Placement) String() string {
	switch p {
	case Changed:
		return "wrote new bytes"
	case Unchanged:
		return "nothing to write"
	}
	return "not placed"
}

// digestOf is what the address answers with today, or nil where it answers with
// nothing.
//
// A file that is there and cannot be read is an error rather than nil. Guessing
// in that direction would report a run as having changed the catalogue on the
// strength of a read that did not happen, which is the shape of claim this
// repository refuses everywhere else.
func digestOf(name string) ([]byte, error) {
	f, err := os.Open(name)
	if errors.Is(err, os.ErrNotExist) {
		return nil, nil
	}
	if err != nil {
		return nil, err
	}
	defer f.Close()

	h := sha256.New()
	if _, err := io.Copy(h, f); err != nil {
		return nil, err
	}
	return h.Sum(nil), nil
}

// Place writes what produce emits to the target, atomically from a reader's
// point of view.
//
// produce takes the writer and no location, which is the half of #31's
// separation that the type system can hold: a generator handed this signature
// cannot decide where its output goes even by accident.
//
// The directory has to exist already. Creating it would turn a target pointed at
// the wrong place into a new empty directory nobody serves, and the run would
// report success while every server kept reading the old address.
//
// A run that produced the bytes already published still renames over them, and
// the verdict it returns is the only thing that differs. Skipping the rename
// there would be cheaper and would leave a file whose mode, owner and any
// damage done to it since the last run all survive, so a catalogue served as a
// refusal would keep being served as one for as long as nothing released.
func Place(root string, t Target, produce func(io.Writer) error) (placed Placement, err error) {
	if t.Dir == "" || t.Name == "" {
		return NotPlaced, fmt.Errorf("a target needs a directory and a file name, and it has %q and %q", t.Dir, t.Name)
	}

	dir := filepath.Join(root, filepath.FromSlash(t.Dir))
	info, err := os.Stat(dir)
	if err != nil {
		return NotPlaced, fmt.Errorf("the directory %s is published from and it could not be read: %w", t.Dir, err)
	}
	if !info.IsDir() {
		return NotPlaced, fmt.Errorf("%s is where %s is published and it is not a directory", t.Dir, t.Name)
	}

	// Read before anything is produced, because after the rename the bytes this
	// is compared against are this run's own and every run reports itself
	// unchanged.
	before, err := digestOf(t.Path(root))
	if err != nil {
		return NotPlaced, fmt.Errorf("reading what %s answers with today: %w", t.Name, err)
	}

	// The temporary file is beside the target rather than in the system's
	// temporary directory, because a rename is atomic only within one
	// filesystem and the two are routinely on different ones. The leading dot
	// keeps it out of what the site publishes if a run is killed between
	// creating it and removing it.
	tmp, err := os.CreateTemp(dir, "."+t.Name+".*")
	if err != nil {
		return NotPlaced, fmt.Errorf("opening a temporary file beside %s: %w", t.Name, err)
	}
	tmpName := tmp.Name()

	// Both are cleanups rather than the path a good run takes: after a
	// successful rename there is no file at tmpName and nothing left open.
	// A cleanup that fails takes the verdict down with the error, so no caller
	// is told what a run placed by a call that also returned a failure.
	defer func() {
		tmp.Close()
		if removeErr := os.Remove(tmpName); removeErr != nil && !errors.Is(removeErr, os.ErrNotExist) && err == nil {
			placed, err = NotPlaced, fmt.Errorf("removing the temporary file %s: %w", filepath.Base(tmpName), removeErr)
		}
	}()

	// The digest is taken off the bytes on their way to the file rather than by
	// reading the file back, so what is compared is what produce emitted.
	after := sha256.New()
	if err := produce(io.MultiWriter(tmp, after)); err != nil {
		return NotPlaced, fmt.Errorf("producing the bytes for %s: %w", t.Name, err)
	}
	if err := tmp.Chmod(mode); err != nil {
		return NotPlaced, fmt.Errorf("setting the mode of %s: %w", t.Name, err)
	}
	// Ordered before the rename rather than left to the close. A rename that
	// publishes a name whose bytes are still in flight is the truncated-file
	// case with the failure moved somewhere nobody is watching.
	if err := tmp.Sync(); err != nil {
		return NotPlaced, fmt.Errorf("flushing %s before publishing it: %w", t.Name, err)
	}
	if err := tmp.Close(); err != nil {
		return NotPlaced, fmt.Errorf("closing %s before publishing it: %w", t.Name, err)
	}

	if err := os.Rename(tmpName, t.Path(root)); err != nil {
		return NotPlaced, fmt.Errorf("placing %s: %w", t.Name, err)
	}

	// An address that answered with nothing has a nil digest here, and the sum
	// of the produced bytes is never nil, so the first run at an address is a
	// change rather than a comparison of two absences.
	if bytes.Equal(before, after.Sum(nil)) {
		return Unchanged, nil
	}
	return Changed, nil
}
