package manifest

import (
	"bytes"
	"encoding/json"
	"fmt"
	"os"
	"strings"
	"testing"
)

const goldenPath = "testdata/golden-manifest.json"

// TestEncodeReproducesTheGoldenFixture decodes the published specimen and
// encodes it again. The two byte streams have to be identical, because the
// specimen is what every other claim about the byte format is measured against
// and a format that only its own encoder agrees with is not a format.
//
// The failure is reported as an offset with the bytes around it rather than as
// a diff of two four-kilobyte strings, because the mistakes this catches are
// single characters and a whole-file dump hides them.
//
// What it does not catch is worth knowing before trusting it. A round trip
// proves the format and not the content: an edit to a checksum, a URL or a
// version inside the fixture is decoded and encoded back unchanged and passes
// here. What reds it is a byte the encoder would not have produced, which is
// what the format is. The content of a generated entry is #25's and #27's to
// refuse, against the release it came from rather than against this file.
func TestEncodeReproducesTheGoldenFixture(t *testing.T) {
	golden := readGolden(t)

	var plugins []Plugin
	if err := json.Unmarshal(golden, &plugins); err != nil {
		t.Fatalf("decoding %s: %v", goldenPath, err)
	}
	if len(plugins) == 0 {
		t.Fatalf("%s decoded to no plugins, so this test would pass on an empty file", goldenPath)
	}

	var got bytes.Buffer
	if err := Encode(&got, plugins); err != nil {
		t.Fatalf("Encode: %v", err)
	}

	if bytes.Equal(golden, got.Bytes()) {
		return
	}
	at := firstDifference(golden, got.Bytes())
	t.Errorf("re-encoding %s does not reproduce it: first difference at byte %d\n want %q\n  got %q\n golden is %d bytes, output is %d bytes",
		goldenPath, at, window(golden, at), window(got.Bytes(), at), len(golden), got.Len())
}

// TestEncodeLeavesMarkupCharactersLiteral is the near miss. encoding/json
// escapes an ampersand, a less-than and a greater-than as \u sequences unless
// the encoder is told not to, and that is the default rather than an unusual
// setting somebody has to reach for. The result is a file a server still parses
// and a changelog that reads & to the person the changelog is for, on every
// plugin whose release notes contain the word "and" as a symbol.
//
// One deleted call in Encode restores the default. This test is what notices,
// and it does not read the fixture, so it keeps noticing if the fixture is ever
// regenerated by the code it is supposed to be checking.
func TestEncodeLeavesMarkupCharactersLiteral(t *testing.T) {
	plugins := []Plugin{{
		GUID:        "0d2f6f0a-1111-4a11-9a11-aaaaaaaaaaaa",
		Name:        "Escaping fixture",
		Description: "Fixture, not a real plugin.",
		Overview:    "Fixture, not a real plugin.",
		Owner:       "Example Owner",
		Category:    "General",
		Versions: []Version{{
			Version:   "1.0.0.0",
			Changelog: "Search & filter now handle <b>markup</b> in titles.\n",
			TargetABI: "10.11.0.0",
			SourceURL: "https://example.com/plugins/escaping_1.0.0.0.zip",
			Checksum:  "00112233445566778899aabbccddeeff",
			Timestamp: "2026-01-05T09:12:44Z",
		}},
	}}

	var got bytes.Buffer
	if err := Encode(&got, plugins); err != nil {
		t.Fatalf("Encode: %v", err)
	}
	out := got.String()

	for _, literal := range []string{"&", "<b>", "</b>"} {
		if !strings.Contains(out, literal) {
			t.Errorf("output does not contain %q literally", literal)
		}
	}
	// The escape sequences are built rather than written out, so that this file
	// cannot be the thing that carries a stray backslash-u into the tree it is
	// checking. 92 is the backslash, and encoding/json writes the hex in lower
	// case.
	const backslash = rune(92)
	for _, r := range []rune{'&', '<', '>'} {
		escape := fmt.Sprintf("%cu%04x", backslash, r)
		if strings.Contains(out, escape) {
			t.Errorf("output contains %s, so the changelog no longer reads as it was written:\n%s", escape, out)
		}
	}
}

// TestEncodeWritesNoPluginsAsAnEmptyArray holds the documented behaviour of the
// nil case. A caller holding nothing has to produce a file a server can read
// rather than the literal null, which a server cannot.
func TestEncodeWritesNoPluginsAsAnEmptyArray(t *testing.T) {
	var got bytes.Buffer
	if err := Encode(&got, nil); err != nil {
		t.Fatalf("Encode: %v", err)
	}
	if want := "[]\n"; got.String() != want {
		t.Errorf("Encode(nil) wrote %q, want %q", got.String(), want)
	}
}

func readGolden(t *testing.T) []byte {
	t.Helper()
	golden, err := os.ReadFile(goldenPath)
	if err != nil {
		t.Fatalf("reading %s: %v", goldenPath, err)
	}
	return golden
}

// firstDifference returns the index of the first byte at which a and b differ,
// or the length of the shorter one when one is a prefix of the other.
func firstDifference(a, b []byte) int {
	n := len(a)
	if len(b) < n {
		n = len(b)
	}
	for i := 0; i < n; i++ {
		if a[i] != b[i] {
			return i
		}
	}
	return n
}

// window returns the bytes around at, for a failure message somebody can read
// without opening the fixture.
func window(b []byte, at int) string {
	const span = 30
	lo := at - span
	if lo < 0 {
		lo = 0
	}
	hi := at + span
	if hi > len(b) {
		hi = len(b)
	}
	return string(b[lo:hi])
}
